name: Build amway-web

on:
  push:
    branches:
      - main

jobs:
  strategy:
    matrix:
      go-version: [ 1.19.x ]
      os: [ ubuntu-latest,macos-latest,windows-latest ]
  docker:
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: {{ secrets.DOCKER_USERNAME }}
          password: {{ secrets.DOCKER_PASSWORD }}
      -
        name: Build amway web
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: {{ secrets.DOCKER_USERNAME }}/{{ secrets.SERVICE_NAME }}:{{ matrix.os }}
